### ISSUE TITLE
Double Assignment of "args"?

### ISSUE THREAD

**Issue by Boronsbruder** [bablokb/simple-dab-radio#1]
https://github.com/bablokb/simple-dab-radio/blob/2d53d7da2c3e9014c5f0cde5839792295e9a2491/files/usr/local/sbin/simple-dab-radio.py#L154-L155

I'm not really used to python, but isn't the second line overwriting the first one's "args"?

**Comment by bablokb** [comment]
Correct 👍. Thank you.

Fixed with https://github.com/bablokb/simple-dab-radio/commit/4ca7605c3aa0f76b45c981c133617fabc8372e08
